version: '3.1'

services:
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "fpg"
    volumes:
      - ./psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"